//
//  SharedStrings.h
//  MyChart
//
//  Copyright © 2010-2023 Epic Systems Corporation. All rights reserved.

#define STR_SHARE_ALERT_TITLE_DATA  NSLocalizedStringFromTableInBundle(@"SHARE1", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Generic alert title for when the app cannot reach the server")
#define STR_SHARE_ALERT_DATA  NSLocalizedStringFromTableInBundle(@"SHARE2", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Generic alert for when the app cannot reach the server")
#define STR_SHARE_BUTTON_OK  NSLocalizedStringFromTableInBundle(@"SHARE3", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Escapes an alert")
#define STR_SHARE_LOADING  NSLocalizedStringFromTableInBundle(@"SHARE4", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text displays while loading a table view cell@LENGTH@22 characters")
#define STR_SHARE_LOADING_MSG  NSLocalizedStringFromTableInBundle(@"SHARE7", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Message appears when data is being retrieved from the server.")
#define STR_SHARE_IS_PCP  NSLocalizedStringFromTableInBundle(@"SHARE20120106100610", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Indicates that a given provider is the patient's PCP. %1$@ is the provider's display name.  %2$@ is the customer's PCP indicator, -PCP- by default.")
#define STR_SHARE_ACC_UNREAD  NSLocalizedStringFromTableInBundle(@"SHARE20140619013820", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text for the blue unread icon that is added to a cell to notify a user that this message is unread.")
#define STR_SHARE_ACC_ATTACHMENT  NSLocalizedStringFromTableInBundle(@"SHARE20140619013853", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text for the attachment icon that is added to a cell to notify a user that this message or test result contains an attachment.")
#define STR_SHARE_ACC_OPEN_MAP  NSLocalizedStringFromTableInBundle(@"SHARE20140619034042", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text for the button to open the map of a provider location.")
#define STR_SHARE_ACC_CALL  NSLocalizedStringFromTableInBundle(@"SHARE20140619034201", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text hint (read after reading the main label and pausing for a few seconds) for the button to call the phone number of the provider.")
#define STR_SHARE_ACC_PHONE  NSLocalizedStringFromTableInBundle(@"SHARE20140619034237", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text for the main voiceover label on the phone button for calling a provider. %1$ is the phone number.")
#define STR_SHARE_ACC_ADDRESS  NSLocalizedStringFromTableInBundle(@"SHARE20140630051325", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text for the button that takes you to a map of an address. Lets user know that the strings being read in %1$@ is the address of the provider or pharmacy.")
#define STR_SHARE_ACC_OCLOCK  NSLocalizedStringFromTableInBundle(@"SHARE20140709031316", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text read when using the datepicker to select the hour. %1$@ is the hour that was just selected.")
#define STR_SHARE_ACC_MINUTES  NSLocalizedStringFromTableInBundle(@"SHARE20140709031408", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text read when using the datepicker to select the minutes. %1$@ is the minute that was just selected.")
#define STR_SHARE_ACC_BACK_BUTTON  NSLocalizedStringFromTableInBundle(@"SHARE20140722093110", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text for the back button for the custom webview (browser).")
#define STR_SHARE_ACC_FORWARD_BUTTON  NSLocalizedStringFromTableInBundle(@"SHARE20140722093210", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text for the forward button for the custom webview (browser).")
#define STR_SHARE_OPEN_EXTLINK_MSG  NSLocalizedStringFromTableInBundle(@"SHARE20140722093258", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Asks user if they want to open a link from the webview in Safari. %1$@ is the link URL. %2$@ is the app name, i.e. MyChart")
#define STR_SHARE_STAY_HERE_BUTTON  NSLocalizedStringFromTableInBundle(@"SHARE20140722093454", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text for the button to cancel an alert.")
#define STR_SHARE_OPEN_LINK_BUTTON  NSLocalizedStringFromTableInBundle(@"SHARE20140722093608", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text for the button to confirm opening a link outside of the mychart app.")
#define STR_SHARE_RELOAD_BUTTON  NSLocalizedStringFromTableInBundle(@"SHARE20140722024943", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Button to reload a webpage.")
#define STR_SHARE_FAILED_LOAD  NSLocalizedStringFromTableInBundle(@"SHARE20140722025006", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text displayed when we are unable to load a particular webpage.")
#define STR_SHARE_KEYBOARD_HIDE  NSLocalizedStringFromTableInBundle(@"SHARE20140407051849", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title for the button that hides the soft keyboard shown on the screen.@LENGTH@15 characters")
#define STR_SHARE_DAY_LABEL  NSLocalizedStringFromTableInBundle(@"SHARE20140911104129", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@String displayed on segmented control that indicates the user is selecting a time range of one day. Currently only used when selecting intervals of data to display in track my health.@LENGTH@10 characters")
#define STR_SHARE_WEEK_LABEL  NSLocalizedStringFromTableInBundle(@"SHARE20140911104406", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@String displayed on segmented control that indicates the user is selecting a time range of one week. Currently only used when selecting intervals of data to display in track my health.@LENGTH@10 characters")
#define STR_SHARE_MONTH_LABEL  NSLocalizedStringFromTableInBundle(@"SHARE20140911104438", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@String displayed on segmented control that indicates the user is selecting a time range of one month. Currently only used when selecting intervals of data to display in track my health.@LENGTH@10 characters")
#define STR_SHARE_YEAR_LABEL  NSLocalizedStringFromTableInBundle(@"SHARE20140911104503", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@String displayed on segmented control that indicates the user is selecting a time range of one year. Currently only used when selecting intervals of data to display in track my health.@LENGTH@10 characters")
#define STR_SHARE_ALL_LABEL  NSLocalizedStringFromTableInBundle(@"SHARE20140911104537", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@String displayed on segmented control that indicates the user is selecting a time range for all available data. Currently only used when selecting intervals of data to display in track my health.@LENGTH@10 characters")
#define STR_SHARE_DATE_RANGE_LABEL  NSLocalizedStringFromTableInBundle(@"SHARE20140913024546", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text displayed for the segmented date control to indicate the dates displayed. %1$@ is the first date and %2$@ is the last date. The first date is before the last date.")
#define STR_SHARE_ACC_DAY_LABEL  NSLocalizedStringFromTableInBundle(@"SHARE20150304012849", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text (read by screenreader) for the day button on the segmented date control. Informs the user that selecting this button will show readings for the current day.")
#define STR_SHARE_ACC_WEEK_LABEL  NSLocalizedStringFromTableInBundle(@"SHARE20150304012954", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text (read by screenreader) for the week button on the segmented date control. Informs the user that selecting this button will show readings for the last week.")
#define STR_SHARE_ACC_MONTH_LABEL  NSLocalizedStringFromTableInBundle(@"SHARE20150304013020", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text (read by screenreader) for the month button on the segmented date control. Informs the user that selecting this button will show readings for the last month.")
#define STR_SHARE_ACC_YEAR_LABEL  NSLocalizedStringFromTableInBundle(@"SHARE20150304013044", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text (read by screenreader) for the year button on the segmented date control. Informs the user that selecting this button will show readings for the last year.")
#define STR_SHARE_ACC_DATE_RANGE_LABEL NSLocalizedStringFromTableInBundle(@"STR_SHARE_ACC_DATE_RANGE_LABEL", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text (read by screenreader) for the date interval on the segmented date control. Informs the user of the current date range selected. %1$@ is the start date. %2$@ is the end date.")
#define STR_SHARE_ACC_DATE_RANGE_TODAY_LABEL NSLocalizedStringFromTableInBundle(@"STR_SHARE_ACC_DATE_RANGE_TODAY_LABEL", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text ( read by screenreader) for the date interval on the segmented date control. Informs the user the current date range selected is today.")
#define STR_SHARE_ACC_BUTTON_TITLE_LOGIN_WITH_USERNAME_AND_PASSWORD NSLocalizedStringFromTableInBundle(@"STR_SHARE_ACC_BUTTON_TITLE_LOGIN_WITH_USERNAME_AND_PASSWORD", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover btton text (read by screenreader) for switching the login view from passcode to username and password mode. %1$@ is server's login ID name, e.g. Username. %2$@ is server's login password name, e.g. Password.")
#define STR_SHARE_QUESTIONNAIRES_TITLE NSLocalizedStringFromTableInBundle(@"SHARE20150601025006", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of questionnaire workflow")
#define STR_SHARE_ACC_DISMISS_POPUP  NSLocalizedStringFromTableInBundle(@"STR_SHARE_ACC_DISMISS_POPUP", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voice over text for the background button that is hidden behind a popup. Informs user that double tapping will dismiss the popup.")
#define STR_SHARE_ALERT_EXCLAMATION _STRC(@"!", @"@CONTEXT@Text to show when the number of alerts for a paticular patient is greater than 99 and thus to big to display in the small red bubble on the patient tab bar.", @"STR_SHARE_ALERT_EXCLAMATION")
#define STR_SHARE_CANCEL_BUTTON NSLocalizedStringFromTableInBundle(@"STR_SHARE_CANCEL_BUTTON", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Button exits an alert without making any changes")
#define STR_SHARE_PATIENT_ESTIMATES NSLocalizedStringFromTableInBundle(@"STR_SHARE_PATIENT_ESTIMATES", @"Shared", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of Patient Estimates")
@interface WPSharedStrings: NSObject

+ (NSString *) accAddress;
+ (NSString *) accPhone;
+ (NSString *) loading;
+ (NSString *) imageCouldNotBeRetrieved;
+ (NSString *) openExtLinkMessage;

@end
