//
//  AppointmentsStrings.h
//  MyChart
//
//  Copyright © 2010-2024 Epic Systems Corporation. All rights reserved.
//

#define STR_APPTS_BUTTON_BACK_CANCEL  NSLocalizedStringFromTableInBundle(@"APPTS20111215030819", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Button takes the user back a step in cancelling an appointment.@LENGTH@10 characters")
#define STR_APPTS_CANCEL_REASON_SELECT  NSLocalizedStringFromTableInBundle(@"APPTS20111215031727", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Header for the selecting a cancellation reason out of a list.")
#define STR_APPTS_SECTION_BODY_VISIT_WEB  NSLocalizedStringFromTableInBundle(@"APPTS20111215031927", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Tells the user to retrieve more information on this particlar appointment from the website.")
#define STR_APPTS_SECTION_HEADER_REASONS  NSLocalizedStringFromTableInBundle(@"APPTS20111215031950", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The section header for the reasons for a past appointment.@LENGTH@38 characters")
#define STR_APPTS_SECTION_HEADER_PT_INSTRUCTIONS  NSLocalizedStringFromTableInBundle(@"APPTS20111215032231", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Section header for the patient instructions associated with a past appointment.@LENGTH@38 characters")
#define STR_APPTS_SECTION_HEADER_DIAGNOSES  NSLocalizedStringFromTableInBundle(@"APPTS20111215032145", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Section header for the diagnoses associated with a past appointment when there more than one diagnoses (or no diagnoses).@LENGTH@38 characters")
#define STR_APPTS_SECTION_HEADER_FOLLOWUP  NSLocalizedStringFromTableInBundle(@"APPTS20111215032301", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Section header for the follow-up instructions associated with a past appointment.@LENGTH@38 characters")
#define STR_APPTS_SECTION_HEADER_MEDS  NSLocalizedStringFromTableInBundle(@"APPTS20111215032653", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Section header for the medications which were prescribed during this past appointment.@LENGTH@38 characters")
#define STR_APPTS_SECTION_HEADER_VITALS  NSLocalizedStringFromTableInBundle(@"APPTS20111215032716", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Section header for the vitals recorded during this past appointment.@LENGTH@38 characters")
#define STR_APPTS_SECTION_HEADER_DIAGNOSIS  NSLocalizedStringFromTableInBundle(@"APPTS20111215032056", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Section header for the diagnoses associated with a past appointment when there is one diagnosis.@LENGTH@38 characters")
#define STR_APPTS_PAST_APPT_LOADING  NSLocalizedStringFromTableInBundle(@"APPTS20111215032952", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Tells the user that the past appointment information is getting loaded.")
#define STR_APPTS_PAST_APPT_NO_INFO  NSLocalizedStringFromTableInBundle(@"APPTS20111215032857", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Lets the user know that the selected past appointment has no information associated with a given section.@LENGTH@37 characters")
#define STR_APPTS_PAST_APPT_DUPLICATE_MEDS_WARNING  NSLocalizedStringFromTableInBundle(@"STR_PAST_APPTS_DUPLICATE_MEDS_WARNING", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Lets the user know that the following list of medications includes potential duplicates.")
#define STR_APPTS_BUTTON_NOT_NOW  NSLocalizedStringFromTableInBundle(@"APPTS20111215041020", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Button closes the alert without making a call.")
#define STR_APPTS_BUTTON_PLACE_CALL  NSLocalizedStringFromTableInBundle(@"APPTS20111215041035", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Button initiates a call with the clinic using the displayed phone number.")
#define STR_APPTS_POPUP_CANCEL_CONFIRM  NSLocalizedStringFromTableInBundle(@"APPTS20111215041325", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Button cancels the dialog without making any changes.")
#define STR_APPTS_BUTTON_CANCEL_FUTURE  NSLocalizedStringFromTableInBundle(@"APPTS20111215041642", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title for button to cancel the appointment.@LENGTH@16 characters")
#define STR_APPTS_BUTTON_CANCEL  NSLocalizedStringFromTableInBundle(@"APPTS2014042223001", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title for button to cancel alert view.@LENGTH@16 characters")
#define STR_APPTS_DEFAULT_VISIT_TYPE  NSLocalizedStringFromTableInBundle(@"APPTS20111215041805", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Displays as the visit type (in the screen header) when there is no visit type attached to the appointment.")
#define STR_APPTS_TITLE_LINKED  NSLocalizedStringFromTableInBundle(@"APPTS20111215042351", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title for the screen for cancelling an appointment linked with other appointments.")
#define STR_APPTS_LABEL_VITALS_BP  NSLocalizedStringFromTableInBundle(@"APPTS20111216132347", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Label for the Blood Pressure field in the vitals section of this appointment.@LENGTH@35 characters")
#define STR_APPTS_LABEL_VITALS_RESPIRATION  NSLocalizedStringFromTableInBundle(@"APPTS20111216103800", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Label for the Respiration field in the vitals section of this appointment.@LENGTH@35 characters")
#define STR_APPTS_LABEL_VITALS_PULSE  NSLocalizedStringFromTableInBundle(@"APPTS20111216103837", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Label for the Pulse field in the vitals section of this appointment.@LENGTH@35 characters")
#define STR_APPTS_LABEL_VITALS_HEIGHT  NSLocalizedStringFromTableInBundle(@"APPTS20111216103839", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Label for the Height field in the vitals section of this appointment.@LENGTH@23 characters")
#define STR_APPTS_LABEL_VITALS_TEMP  NSLocalizedStringFromTableInBundle(@"APPTS20111216103840", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Label for the Temperature field in the vitals section of this appointment.@LENGTH@35 characters")
#define STR_APPTS_LABEL_VITALS_WEIGHT  NSLocalizedStringFromTableInBundle(@"APPTS20111216103842", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Label for the Weight field in the vitals section of this appointment.@LENGTH@20 characters")
#define STR_APPTS_FUTURE_DATE_FORMAT  NSLocalizedStringFromTableInBundle(@"APPTS20111216011305", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Date that appears near the top of the future appointment detail screen, e.g., Thursday, Oct 13, 2011. %1$@ is the localized day of the week, e.g. Thursday.  %2$@ is the localized Apple medium-form date, e.g., Oct 13, 2011.")
#define STR_APPTS_BUTTON_ADD_TO_CALENDAR  NSLocalizedStringFromTableInBundle(@"APPTS20111216015204", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Button initiates adding the selected appointment to the user's calendar app.")
#define STR_APPTS_PROMPT_CANCEL_REASON  NSLocalizedStringFromTableInBundle(@"APPTS20111216020525", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Prompt for the reason for cancelling appointment selection cell.")
#define STR_APPTS_PROMPT_ALSO_CANCEL  NSLocalizedStringFromTableInBundle(@"APPTS20111216020556", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Prompt for the number of linked appointments that must also be cancelled if this one is cancelled.")
#define STR_APPTS_LABEL_REASON_REQUIRED  NSLocalizedStringFromTableInBundle(@"APPTS20111216020631", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@If a cancellation reason is required, this is the hint for selecting a cancellation reason.")
#define STR_APPTS_LABEL_REASON_SELECT  NSLocalizedStringFromTableInBundle(@"APPTS20111216020711", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@If a cancellation reason is not required, this is the hint for selecting a reason.")
#define STR_APPTS_ALERT_TITLE_NO_INFO  NSLocalizedStringFromTableInBundle(@"APPTS20111216020818", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title for alert that appears when a cancellation is attempted without a reason, and a reason is required.")
#define STR_APPTS_ALERT_NO_INFO  NSLocalizedStringFromTableInBundle(@"APPTS20111216020854", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Alert body that appears when a cancellation is attempted without a reason, and a reason is required.")
#define STR_APPTS_BUTTON_OK_CANCEL_APPT  NSLocalizedStringFromTableInBundle(@"APPTS20111216020915", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Button closes an alert when there are no possible changes.")
#define STR_APPTS_ALERT_TITLE_GENERIC_CANCEL  NSLocalizedStringFromTableInBundle(@"APPTS20111216021012", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Alert title appears when an appointment cancellation fails for an unknown reason.")
#define STR_APPTS_ALERT_GENERIC_CANCEL  NSLocalizedStringFromTableInBundle(@"APPTS20111216022551", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Alert appears when an appointment cancellation fails for an unknown reason.")
#define STR_APPTS_COMMENTS_PLACEHOLDER  NSLocalizedStringFromTableInBundle(@"APPTS20140407051740", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Placeholder text that hints the user to add comments while canceling an appointment.")
#define STR_APPTS_ACC_CANCEL_FUTURE  NSLocalizedStringFromTableInBundle(@"APPTS20140630051207", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text for the button to cancel an appointment. Spells out the whole word appointment because voiceover has difficulty reading abbreviations.")
#define STR_APPTS_NOT_SCHEDULED_TITLE  NSLocalizedStringFromTableInBundle(@"APPTS20141231115953", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of the message displayed to the user when the request to accept an appointment offer has failed.")
#define STR_APPTS_NOT_SCHEDULED_RETRY_MSG  NSLocalizedStringFromTableInBundle(@"APPTS20141231120055", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The message displayed to the user when the request to schedule an appointment offer fails but may be successful if they retry again later.")
#define STR_APPTS_NOT_SCHEDULED_MSG  NSLocalizedStringFromTableInBundle(@"APPTS20141231120148", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The message displayed to the user when the request to schedule an appointment offer fails and that offer is no longer available.")
#define STR_APPTS_ALREADY_SCHEDULED_TITLE  NSLocalizedStringFromTableInBundle(@"APPTS20141231120228", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The title of the alert displayed to the user when they try to accept an appointment offer but it fails because it has already been accepted by someone else for them.")
#define STR_APPTS_ALREADY_SCHEDULED_MSG  NSLocalizedStringFromTableInBundle(@"APPTS20141231120329", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The message displayed to the user when they try to accept an appointment offer but it fails because it has already been accepted by someone else for them.")
#define STR_APPTS_DECLINE_OFFER_DECLINE_BTN  NSLocalizedStringFromTableInBundle(@"APPTS20141231124933", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of the button to decline an offer displayed in the confirm declining an appointment offer alert.")
#define STR_APPTS_DIRECTIONS_BTN  NSLocalizedStringFromTableInBundle(@"APPTS20141231125443", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The title of the button to show the directions to get to the appointment's address.@LENGTH@20 characters")
#define STR_APPTS_CALL_BTN  NSLocalizedStringFromTableInBundle(@"APPTS20141231125549", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of the button to send a call this appointment's department.@LENGTH@20 characters")
#define STR_APPTS_DATETIME_STR  NSLocalizedStringFromTableInBundle(@"APPTS20141231013727", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@String used to combine the datetime with the timezone of the department. %1$@ is the day and time and %2$@ is the timezone")
#define STR_APPTS_ARRIVE_BY  NSLocalizedStringFromTableInBundle(@"APPTS20141231014516", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Tells the user the time they should arrive by for their appointment. %1$@ is the arrival time.@LENGTH@30 characters@CONSTRAINTS@Up to 2 lines, each line with a max of 15 characters. Separate lines with \n")
#define STR_APPTS_JOIN_BY  NSLocalizedStringFromTableInBundle(@"STR_APPTS_JOIN_BY", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"CONTEXT@Tells the user the time they should join by for their video visit appointment. %1$@ is the arrival time.@LENGTH@30 characters@CONSTRAINTS@Up to 2 lines, each line with a max of 15 characters. Separate lines with  \n")
#define STR_APPTS_NEW_APPOINTMENT_OFFER  NSLocalizedStringFromTableInBundle(@"APPTS20141231014600", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of the new appointment offer.@LENGTH@15 characters")
#define STR_APPTS_CURRENT_APPOINTMENT_OFFER  NSLocalizedStringFromTableInBundle(@"APPTS20141231014601", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of the current appointment offer.@LENGTH@15 characters")
#define STR_APPTS_ACCEPT_BTN  NSLocalizedStringFromTableInBundle(@"APPTS20141231014838", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of the button to accept the new appointment offer.@LENGTH@10 characters")
#define STR_APPTS_DECLINE_OFFER_LINKED_BTN  NSLocalizedStringFromTableInBundle(@"APPTS20141231015210", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The title of the button to decline an appointment offer for a linked appointment. The user will \"keep\" their current appointment and decline the offer.@LENGTH@10 characters")
#define STR_APPTS_PENDING_MSG  NSLocalizedStringFromTableInBundle(@"APPTS20150112090756", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Message displayed to user when their request to accept an appointment is pending approval. Usualy caused by cross-deployments.")
#define STR_APPTS_DECLINE_FAILED_TITLE  NSLocalizedStringFromTableInBundle(@"APPTS20150112090947", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of the message displayed to the user when their request to decline an appointment offer fails.")
#define STR_APPTS_DECLINE_FAILED_MSG  NSLocalizedStringFromTableInBundle(@"APPTS20150112091106", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Message displayed to the user when their request to decline an appointment offer fails.")
#define STR_APPTS_OFFER_DECLINED_MSG  NSLocalizedStringFromTableInBundle(@"APPTS20150112091453", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Message displayed to the user when they request to accept an appointment offer but it had already been declined by another user.")
#define STR_APPTS_OFFER_DECLINED_TITLE  NSLocalizedStringFromTableInBundle(@"APPTS20150112091416", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of message displayed to the user when they request to accept an appointment offer but it had already been declined by another user.")
#define STR_APPTS_TO_BE_DETERMINED  NSLocalizedStringFromTableInBundle(@"APPTS20150112092214", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text displayed to the user instead of the appointment time when the time for their appointment is still being determined.")
#define STR_APPTS_APPT_SCHEDULED_TITLE  NSLocalizedStringFromTableInBundle(@"APPTS20150112092631", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of message displayed to user when their request to accept an appointment offer was successful.")
#define STR_APPTS_APPT_SCHEDULED_MSG  NSLocalizedStringFromTableInBundle(@"APPTS20150112093119", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Message displayed to user when their request to accept an appointment offer was successful. %1$@ is the date of the appointment and %2$@ is the time of the new appointment.")
#define STR_APPTS_DECLINE_PENDING_MSG  NSLocalizedStringFromTableInBundle(@"APPTS20150112101748", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Message displayed to the user when their request to decline an appointment offer is pending approval. Usually the result of a cross-deployment.")
#define STR_APPTS_ACC_BARCODE_IMAGE  NSLocalizedStringFromTableInBundle(@"APPTS20150112125931", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text to indicate that the image is of a barcode to scan to check in when arriving at an appointment.")
#define STR_APPTS_PENDING_ACCEPT_TITLE  NSLocalizedStringFromTableInBundle(@"APPTS20150113031758", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of the message displayed to the user when their request to accept an appointment offer is pending approval (usually occurs in cross-deployment).")
#define STR_APPTS_PENDING_DECLINE_TITLE  NSLocalizedStringFromTableInBundle(@"APPTS20150113031901", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of the message displayed to the user when their request to decline an appointment offer is pending approval (usually occurs in cross-deployment).")
#define STR_APPTS_ACC_BARCODE_ID  NSLocalizedStringFromTableInBundle(@"APPTS20150114090818", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Voiceover text for the barcode ID label. Informs the user that the numbers are the Barcode ID. %1$@ is the barcode ID. ex. \"Barcode ID 1000015463\"")
#define STR_APPTS_ACC_ARRIVE_BY_BTN  NSLocalizedStringFromTableInBundle(@"APPTS20150114090923", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The voiceover text for the early arrival reason button. Tells the user when to arrive and that tapping this button will give them more information (shows the early arrival reason). %1$@ is the arrival time. ex. \"Arrive by 7:00 PM, tap for more information.\"")
#define STR_APPTS_ACC_ACCEPT_OFFER_BTN  NSLocalizedStringFromTableInBundle(@"APPTS20150114091056", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The voiceover text label for the button to accept an appointment offer from the wait list.")
#define STR_APPTS_ACC_DECLINE_OFFER_BTN  NSLocalizedStringFromTableInBundle(@"APPTS20150114091130", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The voiceover text for the button to decline a stand alone appointment offer from the wait list.")
#define STR_APPTS_ACC_KEEP_APT_BTN  NSLocalizedStringFromTableInBundle(@"APPTS20150114091221", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The voiceover text for the button to decline a linked appointment offer from the wait list. The user will keep their current appointment.")
#define STR_APPTS_ACC_OFFER_CELL_SUMMARY  NSLocalizedStringFromTableInBundle(@"APPTS20150114091257", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The voiceover text for a standalone appointment offer. %1$@ is the visit type of the offered appointment, %2$@ is the date of the offered appointment, %3$@ is the time of the offered appointment, %4$@ is the provider for the offered appointment, %5$@ is the department of the offered appointment, %6$@ is the date the offer will expire, and %7$@ is the time the offer will expire. ex. \"New appointment offer is now available for Office Visit, Thursday, Jan 4 at 9:00 AM with House M.D. in Dermatology Department. This offer expires Wednesday, Jan 3 at 8:00 PM.\"")
#define STR_APPTS_ACC_LINKED_OFFER_CELL_SUMMARY  NSLocalizedStringFromTableInBundle(@"APPTS20150114091715", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The voiceover text for a linked appointment offer. The linked appointment is the original appointment that the user already has. %1$@ is the visit type of the offered appointment, %2$@ is the date of the offered appointment, %3$@ is the time of the offered appointment, %4$@ is the provider for the offered appointment, %5$@ is the department of the offered appointment, %6$@ is the visit type of the linked appointment, %7$@ is the date of the linked appointment, %8$@ is the time of the linked appointment, %9$@ is the provider for the linked appointment, %10$@ is the department of the linked appointment,  %11$@ is the date the offer will expire, and %12$@ is the time the offer will expire. ex. \"New appointment offer is now available for Office Visit, Thursday, Jan 4 at 9:00 AM with House M.D. in Dermatology Department. This will replace the current appointment for Office Visit, Friday, Jan 5 at 6 PM with House M.D. in Dermatology Department. This offer expires Wednesday, Jan 3 at 8:00 PM.\"")
#define STR_APPTS_ACC_DETAILED_APT_CELL_SUMMARY  NSLocalizedStringFromTableInBundle(@"APPTS20150114091716", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The voiceover text for a detailed cell. The period is added to provide a pause. %1$@ is the title label of the cell, %2$@ is the subtitle or detailed label of the cell. ex. \"Confirm Appointment. Confirm now to skip the reminder call for this appointment.\"")
#define STR_APPTS_OFFER_EXPIRED_MSG  NSLocalizedStringFromTableInBundle(@"APPTS20150121061409", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Message displayed to the user in a pop-up when they request to schedule an appointment offer but it had already expired.")
#define STR_APPTS_WAITLIST_AVAILABLE_DETAILS  NSLocalizedStringFromTableInBundle(@"STR_APPTS_WAITLIST_AVAILABLE_DETAILS", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The details text of the cell telling the user what a wait list can do.")
#define STR_APPTS_WAITLIST_AVAILABLE_HEADER  NSLocalizedStringFromTableInBundle(@"STR_APPTS_WAITLIST_AVAILABLE_HEADER", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The title text of the cell telling the user that a wait list is available for this appointment.")
#define STR_APPTS_WAITLIST_AVAILABLE_BUTTON  NSLocalizedStringFromTableInBundle(@"STR_APPTS_WAITLIST_AVAILABLE_BUTTON", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text signifying to the user that the associated button will get them on a wait list for that appointment.")
#define STR_APPTS_ON_WAITLIST_HEADER  NSLocalizedStringFromTableInBundle(@"STR_APPTS_ON_WAITLIST_HEADER", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The title text of the cell telling the user that they are on a wait list for this appointment.")
#define STR_APPTS_ON_WAITLIST_DETAILS  NSLocalizedStringFromTableInBundle(@"STR_APPTS_ON_WAITLIST_DETAILS", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The details text of the cell telling the user what being on a wait list will do.")
#define STR_APPTS_ON_WAITLIST_BUTTON  NSLocalizedStringFromTableInBundle(@"STR_APPTS_ON_WAITLIST_BUTTON", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text associated with a button that tells the user that the button will remove the user from the wait list.")
#define STR_APPTS_RESCHEDULE_BUTTON  NSLocalizedStringFromTableInBundle(@"STR_APPTS_RESCHEDULE_BUTTON", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text displayed on the reschedule button in the future appointment activity")
#define STR_APPTS_RESCHEDULE_OR_CANCEL_BUTTON  NSLocalizedStringFromTableInBundle(@"STR_APPTS_RESCHEDULE_OR_CANCEL_BUTTON", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text displayed on the button which lets the user rechedule or cancel the appoint in the future appointment activity")
#define STR_APPTS_BLANK_VITAL NSLocalizedStringFromTableInBundle(@"STR_APPTS_BLANK_VITAL", @"Appointments", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text displayed when there is is no info recorded for paticular vital in past appt.")

// THIS CLASS SHOULD BE REMOVED LATER
// Since we do not have a solution for accessing strings defined using #defines and _STRC in objective c from Swift, this class serves as the proxy. Once we have a solution, delete this class and use the new system.
// Same goes for WPTestResultsStrings
@interface WPAppointmentsStrings: NSObject

+ (NSString *) accBarcodeImage; 
+ (NSString *) directionsBtn;
+ (NSString *) defaultVisitType;
+ (NSString *) newAppointmentOffer;
+ (NSString *) currentAppointmentOffer;
+ (NSString *) declineOfferLinkedBtn;
+ (NSString *) accKeepAptBtn;
+ (NSString *) accLinkedOfferCellSummary;
+ (NSString *) declineOfferDeclineBtn;
+ (NSString *) accDeclineOfferBtn;
+ (NSString *) accOfferCellSummary;
+ (NSString *) accAcceptOfferBtn;
+ (NSString *) acceptBtn;
+ (NSString *) accBarcodeId;
+ (NSString *) rescheduleOrCancelButton;
+ (NSString *) rescheduleButton;
+ (NSString *) buttonCancelFuture;
+ (NSString *) accCancelFuture;
+ (NSString *) buttonAddToCalendar;
+ (NSString *) waitlistAvailableHeader;
+ (NSString *) waitlistAvailableDetails;
+ (NSString *) waitlistAvailableButton;
+ (NSString *) onWaitlistHeader;
+ (NSString *) onWaitlistDetails;
+ (NSString *) onWaitlistButton;
+ (NSString *) callBtn;
+ (NSString *) accArriveByBtn;

+ (NSString *) videoUserAlreadyConnectedMessage;
+ (NSString *) videoInitializationFailedGenericMessage; 
+ (NSString *) waitListConfirmRemovalAlertMessage;
+ (NSString *) waitListAcceptOfferAlertMessage;

@end
