//
//  SpringboardStrings.h
//  MyChart
//
//  Copyright © 2010-2023 Epic Systems Corporation. All rights reserved.
//

#define STR_SPING_NO_ACTIVITIES  NSLocalizedStringFromTableInBundle(@"SPING20111220124500", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Appears when no iPhone activities are enabled for this user for this patient.")
#define STR_SPING_BUTTON_OK  NSLocalizedStringFromTableInBundle(@"SPING20111220125013", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Button allows the user to close an alert without making any changes.")
#define STR_SPING_LAUNCH_APPSTORE_ALERT_MESSAGE  NSLocalizedStringFromTableInBundle(@"SPING20140122040349", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@This is the alert message indicating the user that the Custom App they are trying to launch is not installed and instead they will be taken to the App Store to install the app. "\n" adds a new line. %1$@ is the Custom App name")
#define STR_SPING_LAUNCH_APPSTORE_ALERT_OK  NSLocalizedStringFromTableInBundle(@"SPING20140122072657", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of the OK button for Alert box to continue to open the App Store. On clicking this button, the user will be taken to the App Store.")
#define STR_SPING_LAUNCH_APPSTORE_ALERT_CANCEL  NSLocalizedStringFromTableInBundle(@"SPING20140122072809", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of the cancel button for Alert box to cancel opening the App Store")
#define STR_SPING_LAUNCH_APPSTORE_ALERT_TITLE  NSLocalizedStringFromTableInBundle(@"SPING20140124034821", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title for the alert view to download an external custom app from the Apple App Store. %1$@ is the App name.")
#define STR_SPING_ACC_PREFERENCES_BUTTON_GREEN  NSLocalizedStringFromTableInBundle(@"SPING20140630040703", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@VoiceOver (accessibility) text for the green preferences button to change the App's theme color to green.")
#define STR_SPING_ACC_PREFERENCES_BUTTON_BLUE  NSLocalizedStringFromTableInBundle(@"SPING20140630040932", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@VoiceOver (accessibility) text for the blue preferences button to change the App's theme color to blue.")
#define STR_SPING_ACC_PREFERENCES_BUTTON_TANGERINE  NSLocalizedStringFromTableInBundle(@"SPING20140630041019", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@VoiceOver (accessibility) text for the tangerine preferences button to change the App's theme color to tangerine.")
#define STR_SPING_ACC_PREFERENCES_BUTTON_TEAL  NSLocalizedStringFromTableInBundle(@"SPING20140630041058", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@VoiceOver (accessibility) text for the teal preferences button to change the App's theme color to teal.")
#define STR_SPING_ACC_PREFERENCES_BUTTON_PURPLE  NSLocalizedStringFromTableInBundle(@"SPING20140630041128", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@VoiceOver (accessibility) text for the purple preferences button to change the App's theme color to purple.")
#define STR_SPING_ACC_PREFERENCES_BUTTON_PINK  NSLocalizedStringFromTableInBundle(@"SPING20140630041211", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@VoiceOver (accessibility) text for the pink preferences button to change the App's theme color to pink.")
#define STR_SPING_ACC_PREFERENCES_BUTTON_MUSTARD  NSLocalizedStringFromTableInBundle(@"SPING20140630041244", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@VoiceOver (accessibility) text for the mustard preferences button to change the App's theme color to mustard.")
#define STR_SPING_ACC_PATIENT_LABEL  NSLocalizedStringFromTableInBundle(@"SPING20140630041542", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@VoiceOver (accessibility) text that is read to the blind user when the focus is on the patient coverflow on the main springboard of the App. %1$@ is the name of the  patient. %2$d patient's index in the coverflow list. %3$d total number of patients whose medical record the MyChart user can access. E.g. 'Medical record: Tom Sawyer. 1 of 3.'")
#define STR_SPING_LOGIN_FASTER_ALERT_TITLE  NSLocalizedStringFromTableInBundle(@"STR_SPING_LOGIN_FASTER_ALERT_TITLE", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@The title of the alert that appears when the user is presented with alternate methods of logging in, passcode and Touch ID.")
#define STR_SPING_LOGIN_FASTER_WITH_TOUCH_ID_PASSCODE  NSLocalizedStringFromTableInBundle(@"STR_SPING_LOGIN_FASTER_WITH_TOUCH_ID_PASSCODE", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Alert message indicating availability of passcode and Touch ID. @LENGTH@108 characters")
#define STR_SPING_LOGIN_FASTER_WITH_FACE_ID_PASSCODE  NSLocalizedStringFromTableInBundle(@"STR_SPING_LOGIN_FASTER_WITH_FACE_ID_PASSCODE", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Alert message indicating availability of passcode and Face ID. @LENGTH@108 characters")
#define STR_SPING_LOGIN_FASTER_WITH_PASSCODE  NSLocalizedStringFromTableInBundle(@"STR_SPING_LOGIN_FASTER_WITH_PASSCODE", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Alert message indicating availability of passcode. @LENGTH@108 characters")
#define STR_SPING_SETUP_NOW_ALERT_BUTTON_TITLE  NSLocalizedStringFromTableInBundle(@"STR_SPING_SETUP_NOW_ALERT_BUTTON_TITLE", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Alert button title to setup passcode or touch id")
#define STR_SPING_DONT_ASK_AGAIN_ALERT_BUTTON_TITLE  NSLocalizedStringFromTableInBundle(@"STR_SPING_DONT_ASK_AGAIN_ALERT_BUTTON_TITLE", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Alert button title to not be prompted to setup passcode or touch id.")
#define STR_SPING_LOGIN_FASTER_CANCEL_BUTTON_LABEL  NSLocalizedStringFromTableInBundle(@"STR_SPING_LOGIN_FASTER_CANCEL_BUTTON_LABEL", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Alert button title to temporarily dismiss the passcode or Touch ID setup message and show it again during next login.")
#define STR_SPING_CANNOT_OPEN_ACTIVITY  NSLocalizedStringFromTableInBundle(@"STR_SPING_CANNOT_OPEN_ACTIVITY", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Alert message when the user tries to open a custom feature on the springboard that maps to a native activity that cannot be found.")
#define STR_SPING_GOALS_TITLE NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_TITLE", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title for goals section header in the patient springboard screen. Should be uppercase")
#define STR_SPING_PROVIDERS_TITLE NSLocalizedStringFromTableInBundle(@"STR_SPING_PROVIDERS_TITLE", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title for  care team section header in the patient springboard screen. Should be uppercase.")
#define STR_SPING_ACTIVITIES_TITLE NSLocalizedStringFromTableInBundle(@"STR_SPING_ACTIVITIES_TITLE", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title for  activities section header in the patient springboard screen.Should be uppercase.")
#define STR_SPING_PROVIDER_PCP NSLocalizedStringFromTableInBundle(@"STR_SPING_PROVIDER_PCP", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text which displays if the provider is PCP. This text shows up in the care team info popup.")
#define STR_SPING_PROVIDER_SEND_MESSAGE NSLocalizedStringFromTableInBundle(@"STR_SPING_PROVIDER_SEND_MESSAGE", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of a button on the provider info popup. Clicking on this button would take the user to create message activity with the provider preselected as the recipient")
#define STR_SPING_PROVIDER_SCHEDULE_APPT NSLocalizedStringFromTableInBundle(@"STR_SPING_PROVIDER_SCHEDULE_APPT", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of a button on the provider info popup. Clicking on this button would take the user to scheduling activity with the provider preselected")
#define STR_SPING_PROVIDER_CLOSE NSLocalizedStringFromTableInBundle(@"STR_SPING_PROVIDER_CLOSE", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Title of a button on the provider info popup. Closes the provider info popup")
#define STR_SPING_GOALS_EQ NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_EQ", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals details label. This text is shown when a certain measurement has to equal a target value. %1$@ is the measurement (ie. LDL, Steps). %2$@ is the target value")
#define STR_SPING_GOALS_NEQ NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_NEQ", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals details label. This text is shown when a measurement has to not equal value. %1$@ is the measurement (ie. LDL, Steps). %2$@ is the target value")
#define STR_SPING_GOALS_LT NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_LT", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals details label. This text is shown when a measurement a has to be less than a certain value. %1$@ is the measurement (ie. LDL, Steps). %2$@ is the target value")
#define STR_SPING_GOALS_GT NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_GT", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals details label. This text is shown when a measurement has to be greater than a certain value. %1$@ is the measurement (ie. LDL, Steps). %2$@ is the target value")
#define STR_SPING_GOALS_LTE NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_LTE", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals details label. This text is shown when a measurement a has to be not greater than a value. %1$@ is the measurement (ie. LDL, Steps). %2$@ is the target value")
#define STR_SPING_GOALS_GTE NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_GTE", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals details label. This text is shown when a measurement a has to be not less than a value. %1$@ is the measurement (ie. LDL, Steps). %2$@ is the target value")
#define STR_SPING_GOALS_GTLT NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_GTLT", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals details label. This text is shown when a measurement has to be between two values. %1$@ is the measurement (ie. LDL, Steps). %2$@ is the lower value. %3$@ is the upper value")
#define STR_SPING_GOALS_GTLTE NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_GTLTE", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals details label. This text is shown when a measurement has to be between two values. Same as STR_SPING_GOALS_GTLT. Currently this string is not used. %1$@ is the measurement (ie. LDL, Steps). %2$@ is the lower value. %3$@ is the upper value")
#define STR_SPING_GOALS_GTELT NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_GTELT", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals details label. This text is shown when a measurement has to be between two values. Same as STR_SPING_GOALS_GTLT. Currently this string is not used. %1$@ is the measurement (ie. LDL, Steps). %2$@ is the lower value. %3$@ is the upper value")
#define STR_SPING_GOALS_GTELTE NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_GTELTE", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals details label. This text is shown when a measurement has to be between two values. Same as STR_SPING_GOALS_GTLT. Currently this string is not used. %1$@ is the measurement (ie. LDL, Steps). %2$@ is the lower value. %3$@ is the upper value")
#define STR_SPING_GOALS_DIET NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_DIET", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals type label. This text displays when the goal type has to do with diet")
#define STR_SPING_GOALS_EXERCISE NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_EXERCISE", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals type label. This text displays when the goal type has to do with exercise")
#define STR_SPING_GOALS_WEIGHT NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_WEIGHT", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals type label. This text displays when the goal type has to do with weight")
#define STR_SPING_GOALS_BP NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_BP", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals type label. This text displays when the goal type has to do with blood pressure")
#define STR_SPING_GOALS_RESULT_COMPONENT NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_RESULT_COMPONENT", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals type label. This text displays when the goal type has to do with Result Components")
#define STR_SPING_GOALS_PATIENT_STARTED NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_PATIENT_STARTED", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals type label. This text displays when the goal type is patient-started")
#define STR_SPING_GOALS_CONTINGENCY NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_CONTINGENCY", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals type label. This text displays when the goal type has to do with Contingency")
#define STR_SPING_GOALS_GENERAL NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_GENERAL", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals type label. This text displays when the goal type is general")
#define STR_SPING_GOALS_NOT_ON_TRACK NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_NOT_ON_TRACK", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals status label. This text is displayed when the user is not meeting the goals target")
#define STR_SPING_GOALS_ON_TRACK NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_ON_TRACK", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals status label. This text is displayed when the user is meeting the goals target")
#define STR_SPING_IMPROVING NSLocalizedStringFromTableInBundle(@"STR_SPING_IMPROVING", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals status label. This text is displayed when the user's values are improving.")
#define STR_SPING_GOALS_NO_CHANGE NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_NO_CHANGE", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals status label. This text is displayed when the user's values haven't change.")
#define STR_SPING_GOALS_WORSENING NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_WORSENING", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals status label. This text is displayed when the user's values are worsening.")
#define STR_SPING_GOALS_BLANK NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_BLANK", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals details label. Displayed when there is no current information reported on the goal.")
#define STR_SPING_GOALS_LAST_REPORTED NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_LAST_REPORTED", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals date label. This shows the date when the last reading was recorded.")
#define STR_SPING_GOALS_NO_PROGRESS NSLocalizedStringFromTableInBundle(@"STR_SPING_GOALS_NO_PROGRESS", @"Springboard", [WPUtil_Locales findMYCStringBundle], @"@CONTEXT@Text that appears on the goals date label. This is shown when no reading have been added at all. Most likely, the goals was newly added.")

@interface WPSpringboardStrings: NSObject

+(NSString *)downloadAppAlertTitle;
+(NSString *)downloadAppAlertMessage;

@end
